const questions = [
"Point at the person who's always on time, if not early.",
"Point to the person who's surprisingly good at drawing or sketching.",
"Point at the person who would prefer to stay home over going out.",
"Point at the person who's most likely to leave something behind everywhere they go.",
"Point at the person who's a master at video games.",
"Point at the person who makes the best last-minute decisions.",
"Point at the person who would be the most fun travel buddy.",
"Point at the person who's best at remembering birthdays without needing a reminder.",
"Point at the person who's always up for an impromptu road trip.",
"Point at the person who's best at diffusing an awkward situation.",
"Point at the person most likely to order a very unusual drink at a bar.",
"Point at the person who would get the most excited about a new gadget.",
"Point to the person who could probably bake the best birthday cake.",
"Point at the person most likely to get a song stuck in their head for days.",
"Point at the person who's definitely a morning person.",
"Point at the person who's always dressed impeccably, even on a casual day.",
"Point at the person who's most likely to accidentally walk into a glass door.",
"Point at the person who always knows the latest gossip.",
"Point at the person most likely to fall asleep during a movie.",
"Point at the person who's best at spotting deals and discounts",
"Point at the person most likely to spontaneously book a trip to a random country.",
"Point to the person who makes friends everywhere they go.",
"Point at the person who would be the first to try a bizarre food combination.",
"Point to the person who gives the best unexpected compliments.",
"Point at the person who's best at finding a bargain.",
"Point at the person who's the best dancer.",
"Point at the person most likely to start a dance party out of nowhere.",
"Point at the person who's always good at games",
"Point at the person most likely to have forgotten someone's birthday this year.",
"Point at the person who's definitely a night person.",
"Point to the person who always seems to know what's going on in Bollywood gossip",
"Point at the person who's best at keeping a secret.",
"Point at the person you think is most likely to win a reality TV show.",
"Point to the person who's the quickest to offer help without being asked.",
"Point at the person who's best at negotiating a deal.",
"Point at the person who tells the best stories.",
"Point at the person who's most likely to win the lottery and not tell anyone.",
"Point at the person who's worst at remembering names and faces.",
"Point at the person who's the group's designated hype person.",
"Point at the person who's always the last to know about a popular trend.",
"Point to the person who probably has the most apps on their phone.",
"Point at the richest person on this table",
"Point to the person who could talk their way out of any sticky situation.",
"Point at the person most likely to believe in ghosts.",
"Point at the person most likely to win an argument with a customer service representative.",
"Point at the person who's best at staying positive no matter what.",
"Point to the person you think has the most elaborate morning routine.",
"Point at the person who's best at giving advice.",
"Point to the person you'd want on your team for a trivia night.",
"Point at the person who's the worst at keeping a straight face.",
"Point at the person who's best at comforting others.",
"Point at the person most likely to win a competitive eating contest.",
"Point at the person who would get surprisingly competitive over a game.",
"Point to the person you'd pick to assemble a complex piece of furniture.",
"Point at the person who's always got a surprising story to tell.",
"Point to the person who could probably make a living as a professional napper.",
"Point at the person who would survive the longest in a zombie apocalypse.",
"Point at the person who would be the most likely to teach you something new right now.",
"Point at the person who's the biggest daredevil of the group.",
"Point to the person who's never afraid to try new things.",
"Point at the person who's the life of the party.",
"Point at the person who's most likely to accidentally cause a minor public scene.",
"Point at the person who's always the calmest in a stressful situation.",
"Point at the person who's most likely to forget where they parked their car.",
"Point to the person who's always got a good recommendation for a book or show.",
"Point at the person most likely to show up to a formal event in casual clothes.",
"Point to the person who's best at pretending to pay attention.",

];

export default questions;