const questions = [
  "How many hours did you sleep last night?",
"How many people in this room do you trust completely?",
"On a scale of 0–10, how good is your singing voice?",
"How many alarms do you set in the morning?",
"On a scale of 0–10, how good is your cooking?",
"How many languages can you say “hello” in?",
"On a scale of 0–10, how weird do you think you are?",
"On a scale of 0–10, how likely are you to survive a zombie apocalypse?",
"How many selfies do you take this week?",
"How many times have you been in love?",
"On a scale of 0–10, how much do you like pineapple on pizza?",
"On a scale of 0–10, how competitive are you?",
"Point as many fingers as many books you have read in the past year",
"Hold up as many fingers as rolls of toilet paper your house runs through in a week",
"On a scale of 0–10, how confident are you that aliens think you're hot?",
 "On a scale of 1-10, how much do you love Shah Rukh Khan?",
"How many chicken nuggets can you fit in your mouth",
"How many group chats are you in where you’ve muted everyone?",
"On a scale of 0–10, how much do you regret your last haircut?",
"From a scale of 1 to 10, how likely are you to laugh in a serious moment?",
"How many hours a day do you spend on your phone (rounded to nearest whole number)?",
"Rate your dancing skills on a scale of 1 to 10",
"Hold up the number of fingers for how many different accents you can do",
"Hold up the number of fingers for how many items on your current bucket list are achievable within a year.",
"Hold up the number of fingers of Himesh Reshammiya song you love.",
"Hold up the number of fingers for how many hours you have spent on Social Media today",
"Hold up the number of fingers for how many days you could realistically survive in the jungle",
"Hold up the number of fingers for how many times you've successfully assembled furniture",
"Hold up the number of fingers for how many languages you can speak",
"Hold up the number of fingers for how many countries you have been to in the last 3 years",
"Hold up the number of fingers for how many years older or younger you feel than your actual age",

];

export default questions;