const questions = [
"On a scale of 0–10, how much do you regret your last haircut?",
"How many group chats are you in where you’ve muted everyone?",
"Hold up the number of fingers for how many hours you have spent on Social Media today",
"Hold up the number of fingers for how many days you could realistically survive in the jungle",
"Hold up the number of fingers for how many times you've successfully assembled furniture",
"How many hours did you sleep last night?",
"Hold up the number of fingers for how many different accents you can do",
"On a scale of 0–10, how confident are you that aliens think you're hot?",
"How many selfies do you take this week?",
"Hold up the number of minutes you can hold your breath underwater",
"How many hours a day do you spend on your phone (rounded to nearest whole number)?",
"Rate your dancing skills on a scale of 0 to 10",
"Hold up the number of fingers for how many languages you can speak",
"Hold up the number of fingers for how many countries you have been to in the last 3 years",
"How manyHimesh Reshammiya songs do you love.",
"On a scale of 1-10, how much do you love Shah Rukh Khan?",
"How many drinks can you hold before you feel buzzed",
"Hold up the number of fingers for how many years older or younger you feel than your actual age",
"On a scale of 0–10, how good is your singing voice?",
"Hold up the number of fingers you can comfortably put in your mouth",
"Hold up as many fingers as rolls of toilet paper your house runs through in a week",
"How many languages can you say “hello” in?",
"On a scale of 0–10, how much do you like pineapple on pizza?",
"How many people in this room do you trust completely?",
"Point as many fingers as many books you have read in the past year",
"How many alarms do you set in the morning?",
"Out of a scale of 0-10, how attractive do you think you are?",
"Out of a scale of 0-10, how intelligent do you think you are?",
"How many times did you go to pee today?",
"Hold up as many fingers as pairs of shoes you own",
"From a scale of 0 to 10, how likely are you to laugh in a serious moment?",
"On a scale of 0–10, how likely are you to survive a zombie apocalypse?",
"On a scale of 0–10, how competitive are you?",
"On a scale of 0–10, how weird do you think you are?",
"How many chicken nuggets can you fit in your mouth",
"Hold up the number of fingers for how many items on your current bucket list are achievable within a year.",
"How many times have you been in love?",
"On a scale of 0–10, how good is your cooking?",

];

export default questions;